services:
  - type: web
    name: garava-official
    env: node
    region: singapore
    plan: free
    rootDir: ./
    buildCommand: bash build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true